_BASE_: FastInst_table_tennis_Base.yaml
MODEL:
  BACKBONE: 
    NAME: "build_resnest_backbone"
  # WEIGHTS: "output/fastinst_s101_table_tennis_det2_0220/model_final.pth" #inference
  RESNETS:
    DEPTH: 101
  FASTINST:
    DEC_LAYERS: 5
OUTPUT_DIR: "output/fastinst_S101_T5_0311"
